apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: count
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 2
      MinScale: 1
      TargetCPUPercent: 80
    StrategyType: execution
  configmaps: null
  environment:
    name: java
    namespace: default
  package:
    functionName: io.fission.api.IotApiVehicles
    packageref:
      name: kc-82d23844-8986-49be-89dc-ac2f44274637
      namespace: default
  resources: {}
  secrets: null
