apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: kc
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 10
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 70
    StrategyType: execution
  configmaps: null
  environment:
    name: java
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: io.fission.kafka.IotConsumer
    packageref:
      name: kc-82d23844-8986-49be-89dc-ac2f44274637
      namespace: default
  resources:
    limits:
      cpu: 200m
    requests:
      cpu: 100m
  secrets: null